OPENAI_API_KEY = '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'
supabase_url = 'https://czrcqevhugmnggkzbqzw.supabase.co'
supabase_key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cmNxZXZodWdtbmdna3picXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTI5NDkzNTcsImV4cCI6MjAwODUyNTM1N30.X83ynSLwfG0CoaZCqGlGuMery7V_kP9362KGi6D53CU'